import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  AlertCircle,
  Building2,
  Check,
  Cog,
  Eye,
  EyeOff,
  HardHat,
  Home,
  LockKeyhole,
  LogIn,
  Mail,
  Recycle,
  Shield,
  Truck
} from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { UserRole } from '../types';

const demoRoles: Array<{
  role: UserRole;
  label: string;
  description: string;
  path: string;
  icon: React.ReactNode;
}> = [
  { role: 'CITIZEN', label: 'Citizen', description: 'Report construction waste and track requests.', path: '/citizen', icon: <Home className="h-5 w-5" /> },
  { role: 'BUILDER', label: 'Builder', description: 'Manage waste generated by active projects.', path: '/citizen', icon: <HardHat className="h-5 w-5" /> },
  { role: 'COLLECTION_TEAM', label: 'Collection Crew', description: 'Manage assigned collection operations and collection proof.', path: '/collection', icon: <Truck className="h-5 w-5" /> },
  { role: 'PROCESSING_TEAM', label: 'Processing Plant', description: 'Track processing, material recovery and recycling.', path: '/processing', icon: <Cog className="h-5 w-5" /> },
  { role: 'ADMIN', label: 'MCC Admin', description: 'Monitor reports, operations, analytics and impact.', path: '/admin', icon: <Shield className="h-5 w-5" /> }
];

const demoAccounts: Record<UserRole, { email: string; password: string }> = {
  CITIZEN: { email: 'citizen@rebuildmysore.demo', password: 'demo123' },
  BUILDER: { email: 'builder@rebuildmysore.demo', password: 'demo123' },
  COLLECTION_TEAM: { email: 'collection@rebuildmysore.demo', password: 'demo123' },
  PROCESSING_TEAM: { email: 'processing@rebuildmysore.demo', password: 'demo123' },
  ADMIN: { email: 'admin@rebuildmysore.demo', password: 'demo123' }
};

export const DemoLoginPage: React.FC = () => {
  const { currentUser, isAuthenticated, isLoading, loginDemo } = useAuth();
  const navigate = useNavigate();
  const [selectedRole, setSelectedRole] = useState<UserRole>('CITIZEN');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [rememberMe, setRememberMe] = useState(true);
  const [error, setError] = useState('');

  const selectedDemoRole = demoRoles.find((demoRole) => demoRole.role === selectedRole) || demoRoles[0];
  const authenticatedRole = currentUser
    ? demoRoles.find((demoRole) => demoRole.role === currentUser.role) || selectedDemoRole
    : selectedDemoRole;

  useEffect(() => {
    if (isAuthenticated && currentUser) {
      navigate(authenticatedRole.path, { replace: true });
    }
  }, [authenticatedRole.path, currentUser, isAuthenticated, navigate]);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setError('');

    if (!email.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      setError('Enter a valid email address to continue.');
      return;
    }

    const account = demoAccounts[selectedRole];
    if (email.trim().toLowerCase() !== account.email || password !== account.password) {
      setError(`The email or password does not match the ${selectedDemoRole.label} demo account.`);
      return;
    }

    try {
      await loginDemo(selectedRole, rememberMe);
      navigate(selectedDemoRole.path, { replace: true });
    } catch {
      setError('Demo access could not be started. Please try again.');
    }
  };

  const useDemoAccount = () => {
    const account = demoAccounts[selectedRole];
    setEmail(account.email);
    setPassword(account.password);
    setError('');
  };

  const selectRole = (role: UserRole) => {
    const account = demoAccounts[role];
    setSelectedRole(role);
    setEmail(account.email);
    setPassword(account.password);
    setError('');
  };

  return (
    <section className="min-h-screen bg-gradient-to-br from-forest-50 via-sand-50 to-white px-4 py-8 sm:px-6 lg:px-10 lg:py-12">
      <div className="mx-auto grid max-w-6xl overflow-hidden rounded-3xl border border-sand-200 bg-white shadow-xl shadow-charcoal-900/10 lg:grid-cols-[0.9fr_1.1fr]">
        <div className="flex flex-col justify-between bg-charcoal-950 p-7 text-white sm:p-10 lg:p-12">
          <div>
            <div className="mb-8 flex items-center gap-3">
              <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-forest-700">
                <Recycle className="h-6 w-6 text-forest-200" />
              </div>
              <div>
                <p className="font-display text-lg font-bold">ReBuild <span className="text-terracotta-400">Mysore</span></p>
                <p className="text-[10px] uppercase tracking-[0.18em] text-sand-400">Civic circularity platform</p>
              </div>
            </div>
            <p className="mb-3 text-xs font-bold uppercase tracking-[0.2em] text-forest-300">Mysuru civic operations</p>
            <h1 className="max-w-md font-display text-3xl font-extrabold leading-tight sm:text-4xl">
              One coordinated path from debris to community value.
            </h1>
            <p className="mt-5 max-w-md text-sm leading-relaxed text-sand-300">
              ReBuild Mysore connects residents, builders, collection crews and processing teams in one traceable construction-waste workflow.
            </p>
          </div>
          <div className="mt-10 flex items-center gap-2 border-t border-charcoal-800 pt-5 text-xs text-sand-400">
            <Building2 className="h-4 w-4 text-terracotta-400" />
            <span>Demo workspace for the Mysuru construction and demolition waste initiative.</span>
          </div>
        </div>

        <div className="p-6 sm:p-10 lg:p-12">
          <div className="mb-7">
            <p className="text-xs font-bold uppercase tracking-[0.18em] text-forest-700">Demo Access</p>
            <h2 className="mt-2 font-display text-2xl font-extrabold text-charcoal-900">Sign in to ReBuild Mysore</h2>
            <p className="mt-2 text-sm text-charcoal-600">Select a role to continue to its workspace.</p>
          </div>

          <div className="mb-7 grid gap-2 sm:grid-cols-2">
            {demoRoles.map(({ role, label, description, icon }) => {
              const isSelected = selectedRole === role;
              return (
                <button
                  key={role}
                  type="button"
                  onClick={() => selectRole(role)}
                  className={`flex items-start gap-3 rounded-xl border p-3 text-left transition focus:outline-none focus:ring-2 focus:ring-forest-500 ${
                    isSelected ? 'border-forest-600 bg-forest-50 ring-1 ring-forest-600' : 'border-sand-200 bg-white hover:border-forest-300 hover:bg-sand-50'
                  }`}
                  aria-pressed={isSelected}
                >
                  <span className={`mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${isSelected ? 'bg-forest-700 text-white' : 'bg-sand-100 text-forest-700'}`}>
                    {icon}
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="flex items-center justify-between gap-2 text-sm font-bold text-charcoal-900">
                      {label}
                      {isSelected && <Check className="h-4 w-4 shrink-0 text-forest-700" />}
                    </span>
                    <span className="mt-0.5 block text-[11px] leading-relaxed text-charcoal-600">{description}</span>
                  </span>
                </button>
              );
            })}
          </div>

          <div className="mb-5 rounded-xl border border-forest-200 bg-forest-50 px-4 py-3">
            <p className="text-sm font-semibold text-forest-900">Login as {selectedDemoRole.label}</p>
            <p className="mt-1 text-xs text-forest-800">The demo account is ready. Continue to open the {selectedDemoRole.label.toLowerCase()} workspace.</p>
          </div>

          <form onSubmit={handleSubmit} noValidate className="space-y-4">
            <label className="block">
              <span className="mb-1.5 block text-xs font-semibold text-charcoal-800">Email address</span>
              <span className="relative block">
                <Mail className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-charcoal-400" />
                <input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="you@example.com" className="w-full rounded-lg border border-sand-300 bg-white py-2.5 pl-10 pr-3 text-sm text-charcoal-900 outline-none transition placeholder:text-charcoal-400 focus:border-forest-600 focus:ring-2 focus:ring-forest-100" />
              </span>
            </label>
            <label className="block">
              <span className="mb-1.5 block text-xs font-semibold text-charcoal-800">Password</span>
              <span className="relative block">
                <LockKeyhole className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-charcoal-400" />
                <input value={password} onChange={(event) => setPassword(event.target.value)} type={showPassword ? 'text' : 'password'} autoComplete="current-password" placeholder="Enter demo password" className="w-full rounded-lg border border-sand-300 bg-white py-2.5 pl-10 pr-10 text-sm text-charcoal-900 outline-none transition placeholder:text-charcoal-400 focus:border-forest-600 focus:ring-2 focus:ring-forest-100" />
                <button type="button" onClick={() => setShowPassword((visible) => !visible)} className="absolute right-2 top-2 rounded-md p-1.5 text-charcoal-500 hover:bg-sand-100 hover:text-charcoal-900" aria-label={showPassword ? 'Hide password' : 'Show password'}>
                  {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                </button>
              </span>
            </label>

            <div className="flex items-center justify-between gap-3">
              <label className="flex items-center gap-2 text-xs text-charcoal-600">
                <input type="checkbox" checked={rememberMe} onChange={(event) => setRememberMe(event.target.checked)} className="h-4 w-4 rounded border-sand-300 text-forest-700 focus:ring-forest-500" />
                Remember this demo session
              </label>
              <button type="button" onClick={useDemoAccount} className="text-[11px] font-semibold text-forest-700 hover:text-forest-900">
                Use demo account
              </button>
            </div>

            {error && (
              <div role="alert" className="flex items-start gap-2 rounded-lg border border-red-200 bg-red-50 px-3 py-2.5 text-xs text-red-700">
                <AlertCircle className="mt-0.5 h-4 w-4 shrink-0" />
                <span>{error}</span>
              </div>
            )}

            <button type="submit" disabled={isLoading} className="flex w-full items-center justify-center gap-2 rounded-lg bg-forest-700 px-4 py-3 text-sm font-semibold text-white shadow-sm transition hover:bg-forest-800 focus:outline-none focus:ring-2 focus:ring-forest-500 focus:ring-offset-2 disabled:cursor-wait disabled:opacity-60">
              {isLoading ? 'Preparing workspace...' : `Login as ${selectedDemoRole.label}`}
              {!isLoading && <LogIn className="h-4 w-4" />}
            </button>
            <p className="text-center text-[11px] leading-relaxed text-charcoal-500">
              Demo accounts are provided for hackathon evaluation. This MVP does not provide production authentication.
            </p>
          </form>
        </div>
      </div>
    </section>
  );
};
